dashboard/urls.py
from django.urls import path
# para USAR url en lugar de PATH
from django.conf.urls import include
# para acceso controlado por LOGEO 
from django.contrib.auth.views import login_required

from . import views

# es necesario importar las VISTAS
from .views import *


urlpatterns = [
    path('', views.index, name='home'),
    # Registro de Usuarios
    path('registro', RegistroUsuario.as_view(), name='nuevoUs'),
    path('misCompetencias/', CompetenciasUsuarioListView.as_view(), name='misComp'),
    path('registroCompetencias/', RegistroCompetenciasView.as_view(), name='nuevasComp'),
    # path('actualizarCompetencias/', ActualizarCompetenciasView.as_view(), name='actualizarComp'),
    path('actualizarCompetencias/<int:pk>', ActualizarCompetenciasView.as_view(), name='actualizarComp'),
    
    # Funciones Ajax
    path(r'detalleCompetencia/', views.DetalleCompetencia, name='ajaxDetalleComp'),
]

formate/urls.py
from django.contrib import admin
# include para agregar las URLS de las app
from django.urls import path, include
# Para los archivos estaticos
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views

# PAra el manejor de error personalizados
from django.conf.urls import handler404, handler500
from dashboard.errorHandling import *
# handler400 = 'dashboard.errorHandling.bad_request' #si hay
# handler401 = 'dashboard.errorHandling.no_autorizado'
# handler403 = 'dashboard.errorHandling.permission_denied' #si hay
handler404 = 'dashboard.errorHandling.no_encontrada' #si hay
handler500 = 'dashboard.errorHandling.server_error'#si hay


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls'), name='appPanel'),
    path('buscador/', include('buscador.urls'), name='appBuscador'),
    # path('modelofastText/', include('prediccion.urls'), name='appPrediccion'),
    path('api_rest/', include('api_rest.urls'), name='api-rest'),
    # Usuarios create
    path('accounts/', include('django.contrib.auth.urls')),
    # iniciar seccion
    path('accounts/login/', views.LoginView.as_view(template_name ='registration/login.html'), name='login'),
    # cerrar seccion
    path('accounts/logout/', views.LogoutView.as_view(template_name = 'registration/logout.html'), name='logout'),
    # Cambiar clave de usuario
    path('accounts/password_change/', views.PasswordChangeView.as_view(template_name = 'registration/password_change_form.html'), name='password_change'),
    path('accounts/password_change/done/', views.PasswordChangeDoneView.as_view(template_name ='registration/password_change_done.html'), name='password_change_done'),
    # restablecer calve (vista y el templeta para el EMAIL literal)
    path('accounts/password_reset', views.PasswordResetView.as_view(template_name ='registration/password_reset_form.html', email_template_name = 'registration/password_reset_email.html'), name='password_reset'),
    path('accounts/password_reset/done/', views.PasswordResetDoneView.as_view(template_name = 'registration/password_reset_done.html'), name='password_reset_done'),
    #A donde nos lleva ras recuperar la registration
    path('accounts/reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name = 'registration/password_reset_confirm.html'), name='password_reset_confirm'),
    #Mensaje que nos mostraria el reseteo de la registration y luego el LOGIN
    path('accounts/reset/done/', views.PasswordResetCompleteView.as_view(template_name = 'registration/password_reset_complete.html'), name='password_reset_complete'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User


class Areas(models.Model):
    idarea = models.AutoField(primary_key=True)
    nameareaen = models.CharField(max_length=155)
    nameareaes = models.CharField(max_length=155)

    class Meta:
        db_table = 'areas'

    def __unicode__(self):
        return "%s - %s" % (self.idarea, self.nameareaes)
    
    def __str__(self):
        return "%s - %s" % (self.idarea, self.nameareaes)


class Competences(models.Model):
    idcompetence = models.AutoField(primary_key=True)
    fkarea = models.ForeignKey(Areas, models.DO_NOTHING, db_column='fkarea')
    codecompetence = models.CharField(max_length=5)
    namecompetenceen = models.CharField(max_length=155)
    namecompetencees = models.CharField(max_length=155)
    descriptioncompetenceen = models.CharField(max_length=350)
    descriptioncompetencees = models.CharField(max_length=350)

    class Meta:
        db_table = 'competences'

    def __unicode__(self):
        return "%s - %s - %s" % (self.idcompetence, self.fkarea, self.namecompetencees)
    
    def __str__(self):
        return "%s" % (self.namecompetencees)
        # return "%s - %s" % (self.namecompetencees, self.descriptioncompetencees)

class Examples(models.Model):
    idexample = models.AutoField(primary_key=True)
    fklevel = models.ForeignKey('Proficiencylevels', models.DO_NOTHING, db_column='fklevel')
    fkcompetence = models.ForeignKey(Competences, models.DO_NOTHING, db_column='fkcompetence')
    titlescenarioen = models.CharField(max_length=155)
    titlescenarioes = models.CharField(max_length=155)
    objectivescenarioen = models.CharField(max_length=155)
    objectivescenarioes = models.CharField(max_length=155)
    descriptionexampleen = models.CharField(max_length=780)
    descriptionexamplees = models.CharField(max_length=780)

    class Meta:
        db_table = 'examples'

    def __unicode__(self):
        return "%d - %d - %d - %s" % (self.idexample, self.fklevel, self.fkcompetence, self.titlescenarioes)


class Groups(models.Model):
    idgroup = models.AutoField(primary_key=True)
    namegroupen = models.CharField(max_length=50)
    namegroupes = models.CharField(max_length=50)

    class Meta:
        db_table = 'groups'

    def __unicode__(self):
        return "%d - %s" % (self.idgroup, self.namegroupes)


class Linecompetences(models.Model):
    idline = models.AutoField(primary_key=True)
    fkcompetence = models.ForeignKey(Competences, models.DO_NOTHING, db_column='fkcompetence')
    fklevel = models.ForeignKey('Proficiencylevels', models.DO_NOTHING, db_column='fklevel')
    verben = models.CharField(max_length=100)
    verbes = models.CharField(max_length=100)
    keywordsen = models.CharField(max_length=100)
    keywordses = models.CharField(max_length=100)
    linecompetenceen = models.CharField(max_length=350)
    linecompetencees = models.CharField(max_length=350)

    class Meta:
        db_table = 'linecompetences'

    def __unicode__(self):
        return "%d - %d - %d" % (self.idline, self.fkcompetence, self.fklevel)


class Proficiencylevels(models.Model):
    idlevel = models.AutoField(primary_key=True)
    fkgroup = models.ForeignKey(Groups, models.DO_NOTHING, db_column='fkgroup')
    namelevelen = models.CharField(max_length=50)
    nameleveles = models.CharField(max_length=50)
    descriptionlevelen = models.CharField(max_length=155)
    descriptionleveles = models.CharField(max_length=155)

    class Meta:
        db_table = 'proficiencylevels'

    def __unicode__(self):
        return "%d - %d - %s" % (self.idlevel, self.fkgroup, self.nameleveles)


class Competenciasusuario(models.Model):
    idregistrocompusuario = models.AutoField(primary_key=True)
    fkcompetence = models.ForeignKey(Competences, models.DO_NOTHING, db_column='fkcompetence')
    fkuser = models.ForeignKey(User, models.DO_NOTHING, db_column='fkuser')
    tiene = models.BooleanField(blank=True, null=True)
    recomendacion = models.TextField(blank=True, null=True)
    
    class Meta:
        db_table = 'competenciasusuario'
        unique_together = (('fkcompetence', 'fkuser'),)
    
    def __str__(self):
        return "%s - %s - %s - %s - %s" % (self.idregistrocompusuario, self.fkcompetence, self.fkuser, self.tiene, self.recomendacion)
    

dashboard/views.py
# Create your views here.
# Redireccionar a paginas
from django.urls import reverse_lazy
# CRUD
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
# se importan los modelos
from dashboard.models import *
# Tipos de salidas a template
from django.shortcuts import render, get_object_or_404
# Para el ajax (registro Competencias)
from django.http import JsonResponse

# necesaro para AJAX
from django.views.decorators.csrf import csrf_exempt

# Formularios (personalizados creados)
from .forms import *
# Usado en consulta lambda para contar por grupos
from django.db.models import Count

# Para las cuenta de usuario (no administradores)
from django.contrib.auth.models import User

# Vistas disponibles solo con autenticacion (LOGEO)
from django.contrib.auth.decorators import login_required

import json

# Para filter competencias del usuario LOGEADO
from django.contrib.auth.mixins import LoginRequiredMixin

# Identificar entidad
# rdflib (Consultamos el sparql)
from rdflib.serializer import Serializer
from collections import OrderedDict
from SPARQLWrapper import SPARQLWrapper, JSON


class RegistroUsuario(CreateView):
    '''
        Registra el usuario al sistema solo usuarios (no administrador), al finalizar redirecciona al login.

            Parametros
            ----------
                CreateView (class): Ayuda a generar el formulario para el registro
    '''
    model = User
    form_class = UsuarioForm
    template_name = "registro.html"
    success_url = reverse_lazy('login')


def index(request):
    resumen = dict()
    resumen['Total de áreas'] = Areas.objects.all().count()
    resumen['Total de competencias'] = Competences.objects.all().count()
    resumen['Total de nivel'] = Groups.objects.all().count()
    resumen['Total de dificultad por nivel'] = Proficiencylevels.objects.all().count()
    resumen['Ejemplos disponibles'] = Examples.objects.all().count()
    # nombAreas = Areas.objects.values_list('nameareaes')
    # nombGrupos = Groups.objects.values_list('namegroupes')
    nombAreacantCopm  = Competences.objects.values('fkarea__nameareaen').annotate(numCompArea=Count('fkarea')).order_by('fkarea')
    nombAreaNumComp = [(*dict_instance.values(),) for dict_instance in nombAreacantCopm]
    # nombAreaNumComp = [f'{value[0]}: {value[1]}' for value in values]
    
    nombCompCantExam = Examples.objects.values('fkcompetence__namecompetenceen').annotate(numExampComp=Count('fkcompetence')).order_by('fkcompetence')[:20]
    nombCompNumExam = [(*dict_instance.values(),) for dict_instance in nombCompCantExam]
    
    nombGrupoCantNiveles = Proficiencylevels.objects.values('fkgroup__namegroupen').annotate(numNivelesGrupo=Count('fkgroup')).order_by('fkgroup')
    nombGrupoNumNiveles = [(*dict_instance.values(),) for dict_instance in nombGrupoCantNiveles]
    # nombGrupoNumNiveles = [f'{value[0]}: {value[1]}' for value in claveValor]
    # print(objModel.__str__)
    # print(objModel.__unicode__)
    cntxtIndex = {
        'nombAreaNumComp': nombAreaNumComp,
        'nombCompNumExam': nombCompNumExam,
        'nombGrupoNumNiveles': nombGrupoNumNiveles,
        'resumen': resumen,
    }
    return render(request, "index.html", cntxtIndex)


class CompetenciasUsuarioListView(LoginRequiredMixin, ListView):
    '''
        Lista las competencias asociadas con el usuario Logeado.

            Parametros
            ----------
                LoginRequiredMixin (class): Ayuda a obtener el ID del usuario
                ListView (class): Genera vista basada en clases
            
            Returns:
            ----------
                QuerySet: Es un dict de objetos que hace referencia a la tabla intermedia usada para el registro
    '''
    model = Competenciasusuario
    template_name = 'competenciasusuario_list.html'
    context_object_name = 'misCompetencias'
    
    def get_queryset(self):
        # print('ID user login\t', self.request.user.id)
        lista = Competenciasusuario.objects.filter(fkuser_id=self.request.user.id).order_by('fkcompetence')
        print('QUERY SET\n', lista)
        return lista


class RegistroCompetenciasView(LoginRequiredMixin, CreateView):
    '''
        Registra las competencias digitales del usuario

            Parametros
            ----------
                LoginRequiredMixin (class): Ayuda a obtener el ID del usuario
                CreateView (class): Genera vista basada en clases para crear.
            
            Returns:
            ----------
                form_valid: Reforna un formulario valido para registrar
    '''
    model = Competenciasusuario
    # form_class = RegistroCompForm
    fields = ['fkcompetence', 'tiene']
    # Aqui empezando el registro de competencia
    template_name = 'competenciasusuario_form.html'
    success_url = reverse_lazy('nuevasComp')
    
    def form_valid(self, form):
        print('ID user logeado\t', self.request.user)
        fkcompetence = form.cleaned_data['fkcompetence']
        tiene = form.cleaned_data['tiene']
        # todo el id del USUARIO LOGEADO
        form.instance.fkuser = self.request.user
        return super().form_valid(form)


class ActualizarCompetenciasView(LoginRequiredMixin, UpdateView):
    '''
        Visualiza los competencias del usuario y el valor con el que fueron guardadas

            Parametros
            ----------
                LoginRequiredMixin (class): Ayuda a obtener el ID del usuario
                CreateView (class): Genera vista basada en clases para crear.
            
            Returns:
            ----------
                form_valid: Reforna un formulario valido para modificar el registro
    '''
    model = Competenciasusuario
    fields = ['tiene']
    template_name = 'competenciasusuario_update.html'
    context_object_name = 'competenciaActual'
    success_url = reverse_lazy('misComp')

    def get_object(self):
        idcompetence = self.kwargs.get("pk")
        print("ID_Competence\t ", idcompetence)
        idUser = self.request.user
        print("ID_User\t ", idUser.id)
        instance = get_object_or_404(Competenciasusuario, fkcompetence = idcompetence, fkuser= idUser.id)
        return instance

    def form_valid(self, form):
        idUser = self.request.user
        idcompetence = self.kwargs.get("pk")
        # idcompetence = self.kwargs.id
        print("ID_User Form\t ", idUser)
        # Toma el ID de la competencia (enviado en la URL)
        print("ID_Competence Form\t ", idcompetence)
        tiene = form.instance.tiene
        user = self.request.user.first_name +" "+ self.request.user.last_name
        print("Usuario Form\t ", user)
        redirect_url = super(ActualizarCompetenciasView, self).form_valid(form)
        updateCompetencia = Competenciasusuario.objects.get(fkuser = idUser, fkcompetence = idcompetence)
        # Trae la competencia a modificar
        updateCompetencia.tiene = tiene
        updateCompetencia.save()
        tiene = form.cleaned_data['tiene']
        return redirect_url


@csrf_exempt
def DetalleCompetencia(request):
    '''
        Ajax que permite obtener el nombre del area y descripcion de la competencias seleccionada

            Parametros
            ----------
                request : request
                    Ayuda a obtener el valor de la funcion ajax
            
            Returns:
            ----------
                JsonResponse: Con el diccionario del detalla requerido
    '''
    if request.is_ajax() == True:
        context ={}
        idComp = request.POST['fkCompetencia']
        # valor que se toma del ajax seccion data
        print('ID competencia selecionada\t', idComp)
        queryset = Competences.objects.get(idcompetence=idComp)
        infoCompetencia = queryset
        print('infoCompetencia\t', infoCompetencia)
        fkArea = infoCompetencia.fkarea
        fkAreaComp = int(fkArea.idarea)
        print('fkAreaComp\t', fkAreaComp)
        queryset = Areas.objects.get(idarea = fkAreaComp)
        infoArea = queryset
        print('infoArea\t', infoArea)
        context['infoArea']= infoArea.nameareaes
        context['infoCompetencia']= infoCompetencia.descriptioncompetencees
        return JsonResponse(context, safe=False)

dashboard/templates/competenciasusuario_form.html
{% extends "master.html" %}
{% load static %}

{% block titulo %}
  Record digital competence
{% endblock %}

{% block contenido %}
  <h1 class="mt-4 text-center">Record digital competence</h1>
  <div class="row">
    <div class="col-xl-12">
      <form class="custom-form" method="POST" action="">
        {% csrf_token %}
        <div class="row">
          <div class="fieldWrapper col-xl-12">
            <div class="row">
              <div class="col-xl-12">
                <label for="{{ form.fkcompetence.id_for_label }}"><b>Digital competence:</b></label>
                {{form.fkcompetence}}
              </div>
              <div class="col-xl-12">
                {% if form.fkcompetence.help_text %}
                  <label class="small mb-1" for="help_textCompetencia">{{ form.fkcompetence.help_text }}</label>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="fieldWrapper col-xl-12">
            <div class="row">
              <div class="col-xl-12">
                <label for="descrip"><b>Area:</b></label>
                <p id="nombre_area"></p>
              </div>
              <div class="col-xl-12">
                <label for="descrip"><b>Description:</b></label>
                <p id="descripcion_competencia"></p>
              </div>
            </div>
          </div>
          <div class="fieldWrapper col-xl-12">
            <div class="row">
              <div class="col-xl-12">
                {{ form.tiene.errors }}
                <label for="{{ form.tiene.id_for_label }}"><b>Do you think you have the competition?</b></label>
                {{ form.tiene }}
              </div>
              <div class="col-xl-12">
                {% if form.tiene.help_text %}
                  <label class="small mb-1 help" for="help_textTiene">{{ form.tiene.help_text|safe }}</label>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-primary btn-user">
            Submit
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}



{% block script %}
  <script type="text/javascript">
    $("#id_fkcompetence").change(function () {// get the url of the `load_cities` view
      var fkCompetencia = $("#id_fkcompetence").val(); // get the selected country ID from the HTML input
      // var x = document.getElementById("fkcompetence").value; // get the selected country ID from the HTML input
      // console.log('fk Competence', fkCompetencia);
      var board_url = "{%  url 'ajaxDetalleComp' %}";
      $.ajax({
        // initialize an AJAX request      
        url: board_url,
        // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        type: "POST",
        data: {
        'fkCompetencia': fkCompetencia,
        // add nombCompetencia to the GET parameters
        //'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
        // add nombCompetencia id to the GET parameters
        },
        datatype:'json',
        success: function(data) {
          console.log('cambio')
          // `data` is the return of the `load_cities` view function
          var nombArea = document.getElementById("nombre_area");
          var descripcionComp = document.getElementById("descripcion_competencia");
          // console.log(data);
          nombArea.innerHTML = data['infoArea'];
          descripcionComp.innerHTML = data['infoCompetencia'];
        }
      });
    });      
  </script>
{% endblock %}

dashboard/templates/competenciasusuario_list.html
{% extends "master.html" %}
{% block titulo %}
    My digital competences
{% endblock %}

{% block contenido %}
    <h1 class="mt-4 text-center">My digital competences</h1>
    <div class="row">
        <div class="col-xl-12">
            <label class="mb-4" for="help_textCompetencia">Those in bold mean you have.</label>
        </div>
        <div class="col-xl-12">
            {% for detalle in misCompetencias %}
                {% if detalle.fkcompetence.fkarea.idarea == 1 %}
                    <div class="card">
                        <div class="card-header" id="{{detalle.fkcompetence.fkarea.idarea}}">
                            <b>Area: </b>{{detalle.fkcompetence.fkarea.nameareaes}}
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">
                                <input type="checkbox" name="{{detalle.fkcompetence.namecompetencees|slugify}}" id="{{detalle.fkcompetence.idcompetence}}" value="{{detalle.tiene}}" {% if detalle.tiene is True %} checked {% endif %} disabled="True">
                                {% if detalle.tiene == True %}
                                    <b class="text-black">{{detalle.fkcompetence.namecompetencees}}</b>
                                {% else %}
                                    {{detalle.fkcompetence.namecompetencees}}
                                {% endif %}
                            </h5>
                            <p class="card-text">
                                <label for="descripcionCompetencia">Description:</label>
                                {{detalle.fkcompetence.descriptioncompetencees}}
                            </p>
                            <a class="btn btn-outline-dark" role="button" href="{% url 'actualizarComp' detalle.fkcompetence.idcompetence %}">Update</a>
                        </div>
                    </div>
                    <br>
                {% elif detalle.fkcompetence.fkarea.idarea == 2 %}
                    <div class="card">
                        <div class="card-header" id="{{detalle.fkcompetence.fkarea.idarea}}">
                            <b>Area: </b>{{detalle.fkcompetence.fkarea.nameareaes}}
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">
                                <input type="checkbox" name="{{detalle.fkcompetence.namecompetencees|slugify}}" id="{{detalle.fkcompetence.idcompetence}}" value="{{detalle.tiene}}" {% if detalle.tiene is True %} checked {% endif %} disabled="True">
                                {% if detalle.tiene == True %}
                                    <b class="text-black">{{detalle.fkcompetence.namecompetencees}}</b>
                                {% else %}
                                    {{detalle.fkcompetence.namecompetencees}}
                                {% endif %}
                            </h5>
                            <p class="card-text">
                                <label for="descripcionCompetencia">Description:</label>
                                {{detalle.fkcompetence.descriptioncompetencees}}
                            </p>
                            <a class="btn btn-outline-dark" role="button" href="{% url 'actualizarComp' detalle.fkcompetence.idcompetence %}">Update</a>
                        </div>
                    </div>
                    <br>
                {% elif detalle.fkcompetence.fkarea.idarea == 3 %}
                    <div class="card">
                        <div class="card-header" id="{{detalle.fkcompetence.fkarea.idarea}}">
                            <b>Area: </b>{{detalle.fkcompetence.fkarea.nameareaes}}
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">
                                <input type="checkbox" name="{{detalle.fkcompetence.namecompetencees|slugify}}" id="{{detalle.fkcompetence.idcompetence}}" value="{{detalle.tiene}}" {% if detalle.tiene is True %} checked {% endif %} disabled="True">
                                {% if detalle.tiene == True %}
                                    <b class="text-black">{{detalle.fkcompetence.namecompetencees}}</b>
                                {% else %}
                                    {{detalle.fkcompetence.namecompetencees}}
                                {% endif %}
                            </h5>
                            <p class="card-text">
                                <label for="descripcionCompetencia">Description:</label>
                                {{detalle.fkcompetence.descriptioncompetencees}}
                            </p>
                            <a class="btn btn-outline-dark" role="button" href="{% url 'actualizarComp' detalle.fkcompetence.idcompetence %}">Update</a>
                        </div>
                    </div>
                    <br>
                {% elif detalle.fkcompetence.fkarea.idarea == 4 %}
                    <div class="card">
                        <div class="card-header" id="{{detalle.fkcompetence.fkarea.idarea}}">
                            <b>Area: </b>{{detalle.fkcompetence.fkarea.nameareaes}}
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">
                                <input type="checkbox" name="{{detalle.fkcompetence.namecompetencees|slugify}}" id="{{detalle.fkcompetence.idcompetence}}" value="{{detalle.tiene}}" {% if detalle.tiene is True %} checked {% endif %} disabled="True">
                                {% if detalle.tiene == True %}
                                    <b class="text-black">{{detalle.fkcompetence.namecompetencees}}</b>
                                {% else %}
                                    {{detalle.fkcompetence.namecompetencees}}
                                {% endif %}
                            </h5>
                            <p class="card-text">
                                <label for="descripcionCompetencia">Description:</label>
                                {{detalle.fkcompetence.descriptioncompetencees}}
                            </p>
                            <a class="btn btn-outline-dark" role="button" href="{% url 'actualizarComp' detalle.fkcompetence.idcompetence %}">Update</a>
                        </div>
                    </div>
                    <br>
                {% else %}
                    <div class="card">
                        <div class="card-header" id="{{detalle.fkcompetence.fkarea.idarea}}">
                            <b>Area: </b>{{detalle.fkcompetence.fkarea.nameareaes}}
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">
                                <input type="checkbox" name="{{detalle.fkcompetence.namecompetencees|slugify}}" id="{{detalle.fkcompetence.idcompetence}}" value="{{detalle.tiene}}" {% if detalle.tiene is True %} checked {% endif %} disabled="True">
                                {% if detalle.tiene == True %}
                                    <b class="text-black">{{detalle.fkcompetence.namecompetencees}}</b>
                                {% else %}
                                    {{detalle.fkcompetence.namecompetencees}}
                                {% endif %}
                            </h5>
                            <p class="card-text">
                                <label for="descripcionCompetencia">Description:</label>
                                {{detalle.fkcompetence.descriptioncompetencees}}
                            </p>
                            <a class="btn btn-outline-dark" role="button" href="{% url 'actualizarComp' detalle.fkcompetence.idcompetence %}">Update</a>
                        </div>
                    </div>
                    <br>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

dashboard/templates/competenciasusuario_update.html
{% extends "master.html" %}
{% block titulo %}
Update digital competences
{% endblock %}

{% block contenido %}
    <h1 class="mt-4 text-center">Update digital competences</h1>
    <div class="row">
        <div class="col-xl-12">
            <form class="custom-form" method="POST" action="">
                {% csrf_token %}
                <div class="row">
                    <div class="fieldWrapper col-xl-12">
                        <div class="row">
                            <div class="col-xl-12">
                                <label for="{{ form.fkcompetence.id_for_label }}"><b>Digital competences:</b></label>
                                {{competenciaActual.fkcompetence.namecompetencees}}
                            </div>
                        </div>
                    </div>
                    <div class="fieldWrapper col-xl-12">
                        <div class="row">
                            <div class="col-xl-12">
                                <label for="descrip">Area:</label>
                                <p id="nombre_area">
                                    {{competenciaActual.fkcompetence.fkarea.nameareaes}}
                                </p>
                            </div>
                            <div class="col-xl-12">
                                <label for="descrip">Description:</label>
                                <p id="descripcion_competencia">
                                    {{competenciaActual.fkcompetence.descriptioncompetencees}}
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="fieldWrapper col-xl-12">
                        <div class="row">
                            <div class="col-xl-12">
                                {{ form.tiene.errors }}
                                <label for="{{ form.tiene.id_for_label }}"><b>Do you think you have the competition?</b></label>
                            </div>
                            <div class="col-xl-12">
                                {{ form.tiene }}
                            </div>
                            <div class="col-xl-12">
                                <label class="small mb-1 help" for="help_textTiene">On screen you can see the current choice.</label>
                                {% if form.tiene.help_text %}
                                    <label class="small mb-1 help" for="help_textTiene">{{ form.tiene.help_text|safe }}</label>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary btn-user">
                            Update
                        </button>
                    </div>
              </form>
        </div>
    </div>
{% endblock %}